### ISSUE TITLE
Error Migrating to SD Card with Migration Tool

### ISSUE THREAD

**Issue by Novine7** [dragoonDorise/EmuDeck#708]
The Migrate Installation tool states 
"Not Enough Space
You need to have at least 7.2g on Undefined
You Currently have  "

7.2g is my current emudeck folder size, my sd card is 512gb.

Tried reformatting SD in steamos, tried cleaning it in windows diskpart then formatting it in steam again.

Same error occurs each time

**Comment by TenaciousDPS** [comment]
I am having the exact same issue.
SDcard is EXT4
Mounted on /run/media/mmcblk0p1

**Comment by arthurcoppintralalere** [comment]
Same for me with "106g". It's also the size of Emulation directory. Does this feature already works ? May be, it's a mistake between sd card free size and internal free size and have more free size in the internal SSD it's a temporary solution (I will investigate later :) )

**Comment by Godsbane** [comment]
This should be solved; please confirm and we can close :)

**Comment by TenaciousDPS** [comment]
Thank you for reaching out to me about this. Though I unfortunately cannot
test it now. I manually did the migrate last night. Maybe the other person
that was having the issue can confirm it for you.

**Comment by Novine7** [comment]
> This should be solved; please confirm and we can close :)

It worked last night since the update, was able to fully migrate with no issues ^^

**Comment by Novine7** [comment]
Issue is now resolved and working as intended

**Comment by Godsbane** [comment]
thank you for confirming

**Comment by oepn** [comment]
I just ran the migration after this update (I was seeing the same error), restarted my Steam Deck when prompted, and now my 512GB SD card is showing as empty and only 2.3GB max capacity. How can I recover my data?

**Comment by Godsbane** [comment]
well, it doesn't remove anything, it's just an rsync copy mechanism. You should still have all of your data.

**Comment by oepn** [comment]
Thanks for the clarifications. I just checked the card and it's definitely still showing as empty on multiple machines (and only 2.3 GB total capacity), so I'm wondering if this is just a really unfortunately timed card failure during the copy process.

**Comment by Godsbane** [comment]
Have you tried fsck?

**Comment by ian-h-chamberlain** [comment]
I was trying to use the migration tool on 2.1.4 to move directories on the same volume (custom directory in internal storage to a different custom directory) and ran into what I think is the same issue?

```
Not enough space
You need to have at least 13G on Valid
You only have 
```

Free space shouldn't be an issue, I have about 100GiB free on the disk, and also the error still seems like it's missing some text. Should this issue be reopened or should I open anew one?

**Comment by Godsbane** [comment]
Make sure you don't have spaces in the path

**Comment by ian-h-chamberlain** [comment]
> Make sure you don't have spaces in the path

I don't think that should be an issue, I'm trying to migrate from `/home/deck/Documents` to `/home/deck/Games`. Is there any additional info I can collect?

**Comment by Godsbane** [comment]
I just worked with someone on this same issue.

@dragoonDorise there is absolutely a bug with the Appimage. It's getting Valid back from the test and trying to use that as the migration path.

**Comment by dragoonDorise** [comment]
Hi @ian-h-chamberlain , found the issue, I just fixed it on dev. Will be fixed on next release
